/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Menu: typeof import('primevue/menu')['default']
    Password: typeof import('primevue/password')['default']
    Placeholder: typeof import('./src/components/Placeholder.vue')['default']
    PlaceholderItem: typeof import('./src/components/PlaceholderItem.vue')['default']
    Popover: typeof import('primevue/popover')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollPanel: typeof import('primevue/scrollpanel')['default']
    ThemeSwitcher: typeof import('./src/components/ThemeSwitcher.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
  export interface GlobalDirectives {
    Ripple: typeof import('primevue/ripple')['default']
  }
}
